package mx.edu.uaz.vistas.usuarios;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Button;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.Upload;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class UsuarioFormDesign extends CssLayout {
    protected TextField tfNombre;
    protected TextField tfApellidos;
    protected TextField tfNombreComision;
    protected TextField tfCorreo;
    protected TextField tfUsuario;
    protected PasswordField pfPassword;
    protected Upload uploadFoto;
    protected Button btnRegistrar;
    protected Button btnCancelar;

    public UsuarioFormDesign() {
        Design.read(this);
    }
}
